### ISSUE TITLE
README - two badges look broken

### ISSUE THREAD

**Issue by revelt** [tunnckoCore/modern-javascript-snippets#2]
Hi Charlike,

Looks like your readme badges are not loading:

<img width="546" alt="broken_badges" src="https://cloud.githubusercontent.com/assets/8344688/22073299/e8e69218-dd9c-11e6-89b0-c6dca04468df.png">

Personally, I abandoned David-DM for deps badges and went for BitHound. David takes ages to load and 90% of times timeout. BitHound is quick. As a bonus they also check code quality (that's extra badge).

**Comment by tunnckoCore** [comment]
It happens not only in that repo. Sometimes they load, some times they fail and I can't do anything.

As about bithound, tried it few times but don't know when will start using it. I'm okey with CodeClimate + Coveralls for the other code analyzing.

**Comment by tunnckoCore** [comment]
Actually I should remove David DM if i don't publish it to npm.

**Comment by revelt** [comment]
True
